### ISSUE TITLE
Make JBoss Conf as Template

### ISSUE THREAD

**Issue by kameshsampath** [rhtconsulting/jboss_eap#12]
Making JBoss standalone service configuration as template to allow JVM and other configurations pushed as part of the play

**Comment by kameshsampath** [comment]
@sherl0cks  and @sabre1041 , I plan to do the following changes to our role to accomodate the fixes for this issue,
* add configuration j2 templates 
* fixing the jboss_eap/tasks/main.yml#173-196, to remove the lineinfile updates as we shall control it via separate control script to handle this 
* handler updates for starting the service, the service will be transperent of domain or standalone as our systemd service conf will pick the right configuration via role variable 
* tasks/jboss_service.yml update for handling template translation updates

please let me know if you guys have further thoughts and any comments

**Comment by sherl0cks** [comment]
Can you please split the template changes into a different set of commits
and PR than the service changes? This will make it easier to collaborate on
each specific topic

**Comment by kameshsampath** [comment]
Yeah I have planned that way, each point I mentioned above will be smaller commits.


Sent from Outlook Mobile






On Sun, May 8, 2016 at 9:43 AM -0700, "sherl0cks" <notifications@github.com> wrote:





Can you please split the template changes into a different set of commits
and PR than the service changes? This will make it easier to collaborate on
each specific topic
On May 8, 2016 8:41 AM, "Kamesh Sampath" <notifications@github.com> wrote:

> @sherl0cks <https://github.com/sherl0cks> and @sabre1041
> <https://github.com/sabre1041> , I plan to do the following changes to
> our role to accomodate the fixes for this issue,
>
>    - add configuration j2 templates
>    - fixing the jboss_eap/tasks/main.yml#173-196, to remove the
>    lineinfile updates as we shall control it via separate control script to
>    handle this
>    - handler updates for starting the service, the service will be
>    transperent of domain or standalone as our systemd service conf will pick
>    the right configuration via role variable
>    - tasks/jboss_service.yml update for handling template translation
>    updates
>
> please let me know if you guys have further thoughts and any comments
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rhtconsulting/jboss_eap/issues/12#issuecomment-217716124>
>


---

**Comment by sherl0cks** [comment]
Fixed #41
