### ISSUE TITLE
Miscellaneous Issues

### ISSUE THREAD

**Issue by sabre1041** [rhtconsulting/jboss_eap#2]
The following issues are found after testing the role

1. Author links broken in README
   1. Andrew Block
   2. Albert Wong
2. BPM reference in `defaults`
   
     # Installs a BPM Suite via Red Hat internal downloads

3. JBoss EAP artifact repository link not valid
   1. The following error is thrown:
```
TASK: [jboss_eap | Download JBoss EAP from Red Hat Customer Portal] *********** 
failed: [eap] => {"dest": "/tmp/jboss-eap-6.4.0.zip", "failed": true, "response": "HTTP Error 410: Gone", "state": "absent", "status_code": 410, "url": "https://access.redhat.com/cspdownload/c0b50c2aa9f906dc202afb44b029bea4/570c62e4/JBEAP-6.4.0/jboss-eap-6.4.0.zip"}
msg: Request failed

FATAL: all hosts have already failed -- aborting
```

**Comment by sherl0cks** [comment]
@sabre1041 let's move 3 to it's own ticket. I suspect this is related to the CDN for the CSP, as that link works just fine for me both from a rest client and the playbook.
