### ISSUE TITLE
Move to pure init.d Scripts

### ISSUE THREAD

**Issue by sherl0cks** [rhtconsulting/jboss_eap#20]
It's what is supported in the docs for EAP 6 & 7. Current impl uses systemd service to delegate to init.d scripts

**Comment by kameshsampath** [comment]
In my example i used to copy the scripts to etc/sysconfig  when adding systemd scripts. IMHO moving them to pure systemd service might require us to write those scripts by ourselves which might add addtional overhead of maintaining them over EAP releases.


Sent from Outlook Mobile



From: sherl0cks

Sent: Friday, 6 May, 9:18 AM

Subject: [rhtconsulting/jboss_eap] Should We Move Back to init.d Scripts (#20)

To: rhtconsulting/jboss_eap



It's what is supported in the docs for EAP 6 & 7. Current impl uses systemd service to delegate to init.d scripts

**Comment by kameshsampath** [comment]
Personal view is to follow this approach for now and refine it later when we have enough bandwidth, I used the init.d approach for fixes in Issue #12

**Comment by sherl0cks** [comment]
Closed in favor of #34
