### ISSUE TITLE
Having EAP Control Script

### ISSUE THREAD

**Issue by kameshsampath** [rhtconsulting/jboss_eap#23]
Shall we have [eapctl.sh](https://github.com/kameshsampath/ansible-middleware-playbooks-orig/blob/master/provisioning/roles/eap/templates/eapctl.sh.j2) in cases where we don't have EAP installed as service and set the bind-address and other settings we do right now in the jboss_eap/main.yml.

**Comment by sherl0cks** [comment]
IMHO - we want to be very prescriptive in this project and that
includeincludes EAP installed as a service. At this time, I don't see value
in supporting alternative mechanisms for installation/management.

**Comment by kameshsampath** [comment]
Got it.


Sent from Outlook Mobile






On Sun, May 8, 2016 at 9:42 AM -0700, "sherl0cks" <notifications@github.com> wrote:





IMHO - we want to be very prescriptive in this project and that
includeincludes EAP installed as a service. At this time, I don't see value
in supporting alternative mechanisms for installation/management.
On May 8, 2016 12:41 AM, "Kamesh Sampath" <notifications@github.com> wrote:

> Shall we have [eapctl.sh](
> https://github.com/kameshsampath/ansible-middleware-playbooks-orig/blob/master/provisioning/roles/eap/templates/eapctl.sh.j2
> ) in cases where we don't have EAP installed as service and set the
> bind-address and other settings we do right now in the jboss_eap/main.yml.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rhtconsulting/jboss_eap/issues/23>
>


---
