### ISSUE TITLE
Creation of Galaxy user

### ISSUE THREAD

**Issue by kameshsampath** [rhtconsulting/jboss_eap#25]
Creating Ansible galaxy user for RH consulting, which will allow us to publish the roles from rhconsultling/jboss_eap repo

**Comment by sherl0cks** [comment]
@kameshsampath this isn't need. See https://www.ansible.com/blog/ansible-galaxy-2-release. Just make sure you import the role from rhtconsulting repo and not your personal repo. I just test this and it works fine.

**Comment by kameshsampath** [comment]
@sherl0cks, i can do that but when the role is exposed to outside world it will be exposed with the user who has imported the role from rhtconsulting/jboss_eap, for instance currently the role is available with my user `kameshsampath.jboss_eap` but I did import the role from `rhtconsulting/jboss_eap`. but for better branding and authenticity I personally feel to have a RH Consulting specific user so that its independent of the contributors.  thoughts ?

**Comment by sherl0cks** [comment]
May you have the wrong permissions? https://galaxy.ansible.com/rhtconsulting/jboss_eap/ was done the way I described...

**Comment by kameshsampath** [comment]
@sherl0cks, my bad i thought the galaxy user prefix would be added to it, but I see the `organisation` name is added as role's prefix
