### ISSUE TITLE
Web and Management Bind Address

### ISSUE THREAD

**Issue by kameshsampath** [rhtconsulting/jboss_eap#40]
Right now the Web and Management Bind Address are set to `0.0.0.0`, Issue #34 added two variables __jboss_eap_bind_web_address__ and __jboss_eap_bind_management_address__ set to *0.0.0.0*. This needs to be set to the ansible host IP address for better security while provisioning, adhering to JBoss guide defaulting to localhost for bind

**Comment by sherl0cks** [comment]
closed by #41
